import * as React from 'react';
import { Helmet } from 'react-helmet'
import Layout from '../components/layout'

export default function Home() {
  return (
    <div>
      <Helmet>
        <title>Maryna Demchenko: data analyst</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <Layout heroContent={<h1 className="title">My CV</h1>}>
        <p>Download PDF</p>
        <p>View my profile on LinkedIn</p>
      </Layout>
    </div>
  )
}
