import * as React from 'react';
import { Helmet } from 'react-helmet'
import Layout from '../components/Layout'
import Section from '../components/Section'

export default function Home() {
  return (
    <div>
      <Helmet>
        <title>Maryna Demchenko: data analyst</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <Layout heroContent={<h1 className="title">My CV</h1>}>
        <Section>
          <p><a target="_blanc" href="/MarynaDemchenkoCV.pdf">Download my CV as PDF</a></p>
          <p><a target="_blanc" href="https://www.linkedin.com/in/marynademchenko/">View my profile on LinkedIn</a></p>
        </Section>
      </Layout>
    </div>
  )
}
