import * as React from 'react';
import { Helmet } from 'react-helmet'
import Layout from '../components/layout'

export default function Home() {
  return (
    <div>
      <Helmet>
        <title>Maryna Demchenko: data analyst</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <Layout heroContent={
        <>
          <p className="title">
            Maryna Demchenko
          </p>
          <p className="subtitle">
            Self-taught data analyst
          </p>
        </>
      }>
        <p>Welcome to my web-site.</p>
        <p>I share my journey to become a data analyst.</p>
        <p>More will come...</p>

      </Layout>
    </div>
  )
}
