import * as React from 'react';
import { Helmet } from 'react-helmet'
import Layout from '../components/Layout'
import { StaticImage } from 'gatsby-plugin-image'
import Section from '../components/Section'

export default function Home() {
  return (
    <div>
      <Helmet>
        <title>Maryna Demchenko: data analyst</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <Layout heroContent={<h1 className="title">My projects</h1>}>
        <Section>
          <div className="columns">
            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                    <a href="#">#css</a> <a href="#">#responsive</a>
                    <br />
                    <time dateTime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                  </div>
                </div>
              </div>
            </div>

            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                    <a href="#">#css</a> <a href="#">#responsive</a>
                    <br />
                    <time dateTime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Section>
      </Layout>
    </div>
  )
}
