import * as React from 'react';
import { Helmet } from 'react-helmet'
import Layout from '../components/Layout'
import Section from '../components/Section'

export default function Home() {
  return (
    <div>
      <Helmet>
        <title>Maryna Demchenko: data analyst</title>
        <meta name="description" content="Generated by create next app" />
      </Helmet>

      <Layout heroContent={<h1 className="title">My projects</h1>}>
        <Section>
          <div className="columns">
            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    My project about <strong>AI professionals</strong>, where they get their bachelor's degree and where they go to put their knowledge into practice.
                    <a target="_blanc" href="https://public.tableau.com/app/profile/maryna6306/viz/AI_professionals_around_the_world/AI_work_and_study"> Link to Tableau Public</a>
                    <br />
                  </div>
                </div>
              </div>
            </div>

            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    The visualization on the <strong>average height of the population of the Earth</strong>, whether the proximity of equators affects the height of the people and where the tallest people live.
                    <a target="_blanc" href="https://public.tableau.com/app/profile/maryna6306/viz/Thehighestnations/Thehighestnations"> Link to Tableau Public</a>
                    <br />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="columns">
            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    The <strong>Market Basket Analysis</strong>, that shows some insights of sales in the bakery. The dataset belongs to "The Bread Basket", a bakery located in Edinburgh.
                    <a target="_blanc" href="https://public.tableau.com/app/profile/maryna6306/viz/SalesintheBakery/Story#1"> Link to Tableau Public</a>
                    <br />
                  </div>
                </div>
              </div>
            </div>

            <div className="column">
              <div className="card">
                <div className="card-content">
                  <div className="content">
                    Dashboards that show the amount of <strong>content on the Netflix platform</strong> classified by category and identify content production leaders for the platform.
                    <a target="_blanc" href="https://public.tableau.com/app/profile/maryna6306/viz/ContentonNetflix/Dashboard1#1"> Link to Tableau Public</a>
                    <br />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Section>
      </Layout>
    </div>
  )
}
